<a href="https://colab.research.google.com/github/marych0/m4ryc/blob/main/uw_starter_file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Download the ACCTG 522 EDGAR helper module
!wget -q https://raw.githubusercontent.com/ashercurtis/Analytics_Mindset_EDGAR_Explorer/main/edgar.py

In [3]:
import edgar

In [5]:
# Configure access to SEC EDGAR
# Replace these values with your own name and UW email address.

edgar.configure(
    name="Mary Cho",
    email="maryecho@uw.edu"
)

print("EDGAR configured:", edgar.is_configured())

EDGAR configured: True

In [13]:
ticker = "AAPL"

cik = edgar.ticker_to_cik(ticker)

print("Ticker:", ticker)
print("CIK:", cik)

Ticker: AAPL
CIK: 0000320193

In [14]:
# CELL 3 — RAW SUBMISSIONS RESPONSE
submissions = edgar.get_submissions(ticker)

print(type(submissions))
print(submissions.keys())

<class 'dict'>
dict_keys(['cik', 'entityType', 'sic', 'sicDescription', 'ownerOrg', 'insiderTransactionForOwnerExists', 'insiderTransactionForIssuerExists', 'name', 'tickers', 'exchanges', 'ein', 'lei', 'description', 'website', 'investorWebsite', 'category', 'fiscalYearEnd', 'stateOfIncorporation', 'stateOfIncorporationDescription', 'addresses', 'phone', 'flags', 'formerNames', 'filings'])

In [15]:
# CELL 4 — EXPLORE THE NESTED STRUCTURE
print(submissions["filings"].keys())

recent = submissions["filings"]["recent"]

print(type(recent))
print(recent.keys())

dict_keys(['recent', 'files'])
<class 'dict'>
dict_keys(['accessionNumber', 'filingDate', 'reportDate', 'acceptanceDateTime', 'act', 'form', 'fileNumber', 'filmNumber', 'items', 'core_type', 'size', 'isXBRL', 'isInlineXBRL', 'isXBRLNumeric', 'primaryDocument', 'primaryDocDescription'])

In [16]:
# CELL 5 — CONVERT RECENT FILINGS TO A DATAFRAME
import pandas as pd

filings = pd.DataFrame(recent)

filings.head()

,accessionNumber,filingDate,reportDate,acceptanceDateTime,act,form,fileNumber,filmNumber,items,core_type,size,isXBRL,isInlineXBRL,isXBRLNumeric,primaryDocument,primaryDocDescription
0,0001140361-26-038674,2026-10-05,2026-10-01,2026-10-06T02:42:45.000Z,,4,,,,4,20288,0,0,0.0,xslF345X06/form4.xml,FORM 4
1,0001140361-26-038672,2026-10-05,2026-10-01,2026-10-06T02:39:10.000Z,,4,,,,4,14780,0,0,0.0,xslF345X06/form4.xml,FORM 4
2,0001140361-26-038669,2026-10-05,2026-10-01,2026-10-06T02:35:24.000Z,,4,,,,4,18851,0,0,0.0,xslF345X06/form4.xml,FORM 4
3,0001140361-26-038667,2026-10-05,2026-10-01,2026-10-06T02:32:06.000Z,,4,,,,4,11578,0,0,0.0,xslF345X06/form4.xml,FORM 4
4,0001958244-26-000636,2026-10-02,,2026-10-03T01:17:10.000Z,33,144,001-36743,261437893,,144,5383,0,0,0.0,xsl144X01/primary_doc.xml,

In [23]:
# CELL 6 — WHAT TYPES OF FORMS DOES THIS COMPANY FILE?
filings["form"].value_counts()

form
4                 597
8-K               102
144                49
424B2              42
10-Q               33
PX14A6G            27
SC 13G/A           22
FWP                21
3                  12
DEFA14A            12
10-K               11
DEF 14A            11
SD                 11
NO ACT              7
S-3ASR              4
8-A12B              4
S-8                 4
25-NSE              4
S-8 POS             3
UPLOAD              3
CORRESP             3
8-K/A               2
CERTNYS             2
IRANNOTICE          2
SCHEDULE 13G/A      2
CERT                2
144/A               1
SCHEDULE 13G        1
5                   1
4/A                 1
PX14A6N             1
3/A                 1
SC 13G              1
25                  1
Name: count, dtype: int64

In [24]:
# CELL 7 — USE THE CONVENIENCE FUNCTION AFTER UNDERSTANDING THE STRUCTURE
filings_fast = edgar.get_filings(ticker)

filings_fast.head()

,accessionNumber,filingDate,reportDate,acceptanceDateTime,act,form,fileNumber,filmNumber,items,core_type,size,isXBRL,isInlineXBRL,isXBRLNumeric,primaryDocument,primaryDocDescription
0,0001140361-26-038674,2026-10-05,2026-10-01,2026-10-06T02:42:45.000Z,,4,,,,4,20288,0,0,0.0,xslF345X06/form4.xml,FORM 4
1,0001140361-26-038672,2026-10-05,2026-10-01,2026-10-06T02:39:10.000Z,,4,,,,4,14780,0,0,0.0,xslF345X06/form4.xml,FORM 4
2,0001140361-26-038669,2026-10-05,2026-10-01,2026-10-06T02:35:24.000Z,,4,,,,4,18851,0,0,0.0,xslF345X06/form4.xml,FORM 4
3,0001140361-26-038667,2026-10-05,2026-10-01,2026-10-06T02:32:06.000Z,,4,,,,4,11578,0,0,0.0,xslF345X06/form4.xml,FORM 4
4,0001958244-26-000636,2026-10-02,,2026-10-03T01:17:10.000Z,33,144,001-36743,261437893,,144,5383,0,0,0.0,xsl144X01/primary_doc.xml,

In [25]:
# CELL 8 — COMPANY FACTS: RAW XBRL RESPONSE
facts = edgar.get_company_facts(ticker)

print(type(facts))
print(facts.keys())

<class 'dict'>
dict_keys(['cik', 'entityName', 'facts'])

In [27]:
# CELL 9 — EXPLORE THE TAXONOMY
print(facts["facts"].keys())

us_gaap = facts["facts"]["us-gaap"]

print(type(us_gaap))
print(list(us_gaap.keys())[:20])

dict_keys(['dei', 'us-gaap'])
<class 'dict'>
['AccountsPayable', 'AccountsPayableCurrent', 'AccountsReceivableNetCurrent', 'AccruedIncomeTaxesCurrent', 'AccruedIncomeTaxesNoncurrent', 'AccruedLiabilities', 'AccruedLiabilitiesCurrent', 'AccruedMarketingCostsCurrent', 'AccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment', 'AccumulatedOtherComprehensiveIncomeLossAvailableForSaleSecuritiesAdjustmentNetOfTax', 'AccumulatedOtherComprehensiveIncomeLossCumulativeChangesInNetGainLossFromCashFlowHedgesEffectNetOfTax', 'AccumulatedOtherComprehensiveIncomeLossForeignCurrencyTranslationAdjustmentNetOfTax', 'AccumulatedOtherComprehensiveIncomeLossNetOfTax', 'AdjustmentsToAdditionalPaidInCapitalSharebasedCompensationRequisiteServicePeriodRecognitionValue', 'AdjustmentsToAdditionalPaidInCapitalTaxEffectFromShareBasedCompensation', 'AdvertisingExpense', 'AllocatedShareBasedCompensationExpense', 'AllowanceForDoubtfulAccountsReceivableCurrent', 'AmortizationOfIntangibleAssets', 'AntidilutiveSecuritiesExcludedFromComputationOfEarningsPerShareAmount']

In [28]:
# CELL 10 — NOW USE THE MODULE TO LIST CONCEPTS
concepts = edgar.list_facts(ticker)

concepts.head()

,concept,label,description
0,AccountsPayable,Accounts Payable (Deprecated 2009-01-31),Carrying value as of the balance sheet date of...
1,AccountsPayableCurrent,"Accounts Payable, Current",Carrying value as of the balance sheet date of...
2,AccountsReceivableNetCurrent,"Accounts Receivable, after Allowance for Credi...","Amount, after allowance for credit loss, of ri..."
3,AccruedIncomeTaxesCurrent,"Accrued Income Taxes, Current",Carrying amount as of the balance sheet date o...
4,AccruedIncomeTaxesNoncurrent,"Accrued Income Taxes, Noncurrent",Carrying amount as of the balance sheet date o...